const loginView = document.querySelector("#loginView");
const portalView = document.querySelector("#portalView");
const loginForm = document.querySelector("#loginForm");
const logoutButton = document.querySelector("#logoutButton");
const pageTitle = document.querySelector("#pageTitle");
const navItems = Array.from(document.querySelectorAll(".nav-item"));
const languageButtons = Array.from(document.querySelectorAll(".language-button"));

const pages = {
  dashboard: document.querySelector("#dashboardPage"),
  profile: document.querySelector("#profilePage"),
  school: document.querySelector("#schoolPage"),
  career: document.querySelector("#careerPage"),
  alumni: document.querySelector("#alumniPage"),
};

const translations = {
  ja: {
    appTitle: "学生ポータル | 入学後サポート",
    heroEyebrow: "Interview Passed Student Portal",
    heroTitle: "入学手続きから卒業後まで、ひとつのポータルで管理",
    stageEnrollment: "入学手続き",
    stageEnrollmentDesc: "本人情報・書類確認",
    stageSchoolLife: "在校中",
    stageSchoolLifeDesc: "出席・成績・課題",
    stageGraduation: "卒業",
    stageGraduationDesc: "進路・証明情報",
    stageAfterGraduation: "卒業後",
    stageAfterGraduationDesc: "就職先・資格更新",
    studentLogin: "学生ログイン",
    loginHelp: "面接合格後の手続き状況を確認できます。",
    studentId: "学生ID",
    password: "パスワード",
    login: "ログイン",
    sampleLogin: "サンプル: S2026-001 / password",
    portalName: "学生ポータル",
    navDashboard: "ダッシュボード",
    navProfile: "本人情報",
    navSchool: "学校管理情報",
    navCareer: "卒業・進路",
    navAlumni: "卒業後更新",
    logout: "ログアウト",
    welcome: "Welcome",
    studentStatus: "入学手続き中",
    currentStage: "Current Stage",
    currentStageTitle: "面接合格後の入学手続き",
    currentStageText: "本人情報を入力し、学校からの確認結果を待ってください。",
    journeyEnrollmentText: "本人情報、連絡先、緊急連絡先、希望コースを登録",
    journeySchoolText: "出席率、成績、課題、お知らせを確認",
    journeyGraduationText: "卒業情報、進路、就職活動を管理",
    journeyAlumniText: "就職先、転職、資格、同窓生情報を更新",
    nextTasks: "次に必要なこと",
    taskBasic: "基本情報の確認",
    taskAddress: "住所・電話番号の更新",
    taskEmergency: "緊急連絡先の登録",
    taskDocs: "入学書類の提出",
    schoolNotices: "学校からのお知らせ",
    noticeOrientation: "入学説明会",
    noticeOrientationText: "9月3日 10:00 教室A",
    noticeAddress: "住所確認",
    noticeAddressText: "本人情報を最新にしてください",
    noticeCareer: "キャリア面談",
    noticeCareerText: "希望進路アンケートを登録できます",
    profileCategory: "学生本人が入力する情報",
    profileHeading: "学生本人が入力・更新する情報",
    fullName: "氏名",
    kana: "ふりがな",
    birthday: "生年月日",
    nationality: "国籍",
    address: "住所",
    phone: "電話番号",
    email: "メール",
    desiredCourse: "希望コース",
    courseIt: "ITビジネスコース",
    courseJapanese: "日本語コース",
    courseCare: "介護コース",
    emergencyContact: "緊急連絡先",
    careerHope: "就職希望",
    careerHopeValue: "日本でITサポートの仕事を希望しています。",
    save: "保存する",
    profileSaved: "保存しました。学校確認をお待ちください。",
    schoolCategory: "学校が管理する情報",
    schoolHeading: "学校が確認・更新する情報",
    metricStudentNumber: "学生番号",
    metricAttendance: "出席率",
    metricGrade: "平均成績",
    metricAssignments: "課題提出",
    schoolStatus: "学校管理状況",
    tableItem: "項目",
    tableStatus: "状況",
    tableOwner: "担当",
    rowDocs: "入学書類確認",
    rowTuition: "学費確認",
    rowAssignments: "課題提出状況",
    rowNotice: "学校からのお知らせ",
    statusDone: "確認済み",
    statusChecking: "確認中",
    statusMissing: "2件未提出",
    statusSent: "3件配信",
    ownerOffice: "事務局",
    ownerAccounting: "会計",
    ownerTeacher: "担任",
    ownerSchool: "学校",
    careerHeading: "卒業・進路情報",
    careerRegister: "進路登録",
    expectedGraduation: "卒業予定日",
    desiredPath: "希望進路",
    pathWorkJapan: "日本で就職",
    pathStudy: "進学",
    pathReturn: "帰国",
    pathUndecided: "未定",
    desiredJob: "希望職種",
    desiredJobValue: "ITサポート / 事務",
    jobHunting: "就職活動",
    resume: "履歴書作成",
    waitingSchool: "学校確認待ち",
    interviewPractice: "面接練習",
    canReserve: "予約可能",
    companyIntro: "企業紹介",
    threeCompanies: "3社候補あり",
    alumniCategory: "卒業後に更新する情報",
    alumniHeading: "卒業生・Alumni 情報",
    currentCompany: "現在の就職先",
    jobType: "職種",
    workLocation: "勤務地",
    certifications: "取得資格",
    alumniMemo: "転職・近況メモ",
    alumniMemoValue: "卒業後も学校と連絡を取り、後輩への会社紹介も可能です。",
    updateAlumni: "卒業後情報を更新",
    alumniSaved: "卒業後情報を更新しました。",
  },
  my: {
    appTitle: "ကျောင်းသား Portal | ဝင်ခွင့်ပြီးနောက် ပံ့ပိုးမှု",
    heroEyebrow: "Interview Passed Student Portal",
    heroTitle: "ဝင်ခွင့်လုပ်ငန်းစဉ်မှ ဘွဲ့ရပြီးနောက်အထိ တစ်နေရာတည်းတွင် စီမံနိုင်သည်",
    stageEnrollment: "ဝင်ခွင့်လုပ်ငန်းစဉ်",
    stageEnrollmentDesc: "ကိုယ်ရေးအချက်အလက်・စာရွက်စာတမ်း",
    stageSchoolLife: "ကျောင်းတက်နေစဉ်",
    stageSchoolLifeDesc: "တက်ရောက်မှု・အမှတ်・အလုပ်ပေးစာ",
    stageGraduation: "ဘွဲ့ရခြင်း",
    stageGraduationDesc: "အနာဂတ်လမ်းကြောင်း・အထောက်အထား",
    stageAfterGraduation: "ဘွဲ့ရပြီးနောက်",
    stageAfterGraduationDesc: "အလုပ်နေရာ・အောင်လက်မှတ် update",
    studentLogin: "ကျောင်းသား Login",
    loginHelp: "အင်တာဗျူးအောင်ပြီးနောက် လုပ်ငန်းစဉ်အခြေအနေကို စစ်နိုင်သည်။",
    studentId: "ကျောင်းသား ID",
    password: "Password",
    login: "Login ဝင်ရန်",
    sampleLogin: "နမူနာ: S2026-001 / password",
    portalName: "ကျောင်းသား Portal",
    navDashboard: "Dashboard",
    navProfile: "ကိုယ်ရေးအချက်အလက်",
    navSchool: "ကျောင်းစီမံအချက်အလက်",
    navCareer: "ဘွဲ့・အနာဂတ်လမ်းကြောင်း",
    navAlumni: "ဘွဲ့ရပြီးနောက် Update",
    logout: "Logout",
    welcome: "မင်္ဂလာပါ",
    studentStatus: "ဝင်ခွင့်လုပ်ငန်းစဉ်အတွင်း",
    currentStage: "လက်ရှိအဆင့်",
    currentStageTitle: "အင်တာဗျူးအောင်ပြီးနောက် ဝင်ခွင့်လုပ်ငန်းစဉ်",
    currentStageText: "ကိုယ်ရေးအချက်အလက်ဖြည့်ပြီး ကျောင်းဘက်မှ အတည်ပြုချက်ကို စောင့်ပါ။",
    journeyEnrollmentText: "ကိုယ်ရေးအချက်အလက်၊ ဆက်သွယ်ရန်၊ အရေးပေါ်ဆက်သွယ်ရန်၊ သင်တန်းရွေးချယ်မှုကို ဖြည့်ရန်",
    journeySchoolText: "တက်ရောက်မှုနှုန်း၊ အမှတ်၊ အလုပ်ပေးစာ၊ ကြေညာချက်များကို စစ်ရန်",
    journeyGraduationText: "ဘွဲ့ရအချက်အလက်၊ အနာဂတ်လမ်းကြောင်း၊ အလုပ်ရှာဖွေမှုကို စီမံရန်",
    journeyAlumniText: "အလုပ်နေရာ၊ အလုပ်ပြောင်း၊ အောင်လက်မှတ်၊ Alumni အချက်အလက် update လုပ်ရန်",
    nextTasks: "နောက်လုပ်ရန်အရာများ",
    taskBasic: "အခြေခံအချက်အလက် စစ်ဆေးရန်",
    taskAddress: "လိပ်စာ・ဖုန်းနံပါတ် update လုပ်ရန်",
    taskEmergency: "အရေးပေါ်ဆက်သွယ်ရန် ထည့်ရန်",
    taskDocs: "ဝင်ခွင့်စာရွက်စာတမ်း တင်ရန်",
    schoolNotices: "ကျောင်းမှ ကြေညာချက်များ",
    noticeOrientation: "ဝင်ခွင့်ရှင်းလင်းပွဲ",
    noticeOrientationText: "စက်တင်ဘာ 3 ရက် 10:00 Classroom A",
    noticeAddress: "လိပ်စာအတည်ပြုရန်",
    noticeAddressText: "ကိုယ်ရေးအချက်အလက်ကို နောက်ဆုံးအခြေအနေဖြစ်အောင် ပြင်ပါ",
    noticeCareer: "Career ဆွေးနွေးမှု",
    noticeCareerText: "လိုချင်သောအနာဂတ်လမ်းကြောင်း survey ဖြည့်နိုင်သည်",
    profileCategory: "ကျောင်းသားကိုယ်တိုင်ဖြည့်သော အချက်အလက်",
    profileHeading: "ကျောင်းသားကိုယ်တိုင် ဖြည့်・update လုပ်သော အချက်အလက်",
    fullName: "အမည်",
    kana: "ဖူရီဂါနာ",
    birthday: "မွေးနေ့",
    nationality: "နိုင်ငံသား",
    address: "လိပ်စာ",
    phone: "ဖုန်းနံပါတ်",
    email: "Email",
    desiredCourse: "လိုချင်သော Course",
    courseIt: "IT Business Course",
    courseJapanese: "Japanese Course",
    courseCare: "Care Course",
    emergencyContact: "အရေးပေါ်ဆက်သွယ်ရန်",
    careerHope: "အလုပ်အကိုင်မျှော်မှန်းချက်",
    careerHopeValue: "ဂျပန်တွင် IT support အလုပ်လုပ်ချင်ပါသည်။",
    save: "သိမ်းရန်",
    profileSaved: "သိမ်းပြီးပါပြီ။ ကျောင်း၏အတည်ပြုချက်ကို စောင့်ပါ။",
    schoolCategory: "ကျောင်းက စီမံသော အချက်အလက်",
    schoolHeading: "ကျောင်းက စစ်ဆေး・update လုပ်သော အချက်အလက်",
    metricStudentNumber: "ကျောင်းသားနံပါတ်",
    metricAttendance: "တက်ရောက်မှုနှုန်း",
    metricGrade: "ပျမ်းမျှအမှတ်",
    metricAssignments: "အလုပ်ပေးစာတင်ခြင်း",
    schoolStatus: "ကျောင်းစီမံမှုအခြေအနေ",
    tableItem: "အချက်",
    tableStatus: "အခြေအနေ",
    tableOwner: "တာဝန်ခံ",
    rowDocs: "ဝင်ခွင့်စာရွက်စာတမ်း စစ်ဆေးခြင်း",
    rowTuition: "ကျောင်းလခ စစ်ဆေးခြင်း",
    rowAssignments: "အလုပ်ပေးစာတင်မှုအခြေအနေ",
    rowNotice: "ကျောင်းမှ ကြေညာချက်",
    statusDone: "အတည်ပြုပြီး",
    statusChecking: "စစ်ဆေးနေသည်",
    statusMissing: "2 ခု မတင်ရသေး",
    statusSent: "3 ခု ပို့ပြီး",
    ownerOffice: "ရုံးဌာန",
    ownerAccounting: "ငွေစာရင်း",
    ownerTeacher: "အတန်းပိုင်ဆရာ",
    ownerSchool: "ကျောင်း",
    careerHeading: "ဘွဲ့・အနာဂတ်လမ်းကြောင်း အချက်အလက်",
    careerRegister: "အနာဂတ်လမ်းကြောင်း မှတ်ပုံတင်",
    expectedGraduation: "ဘွဲ့ရမည့်ရက်",
    desiredPath: "လိုချင်သောလမ်းကြောင်း",
    pathWorkJapan: "ဂျပန်တွင် အလုပ်လုပ်မည်",
    pathStudy: "ဆက်လက်ပညာသင်မည်",
    pathReturn: "မိမိနိုင်ငံပြန်မည်",
    pathUndecided: "မဆုံးဖြတ်ရသေး",
    desiredJob: "လိုချင်သောအလုပ်အမျိုးအစား",
    desiredJobValue: "IT Support / Office Work",
    jobHunting: "အလုပ်ရှာဖွေမှု",
    resume: "Resume ပြင်ဆင်ခြင်း",
    waitingSchool: "ကျောင်းစစ်ဆေးမှုစောင့်နေသည်",
    interviewPractice: "Interview လေ့ကျင့်ခြင်း",
    canReserve: "Reservation လုပ်နိုင်သည်",
    companyIntro: "ကုမ္ပဏီမိတ်ဆက်",
    threeCompanies: "ကုမ္ပဏီ 3 ခု ရှိသည်",
    alumniCategory: "ဘွဲ့ရပြီးနောက် update လုပ်သော အချက်အလက်",
    alumniHeading: "ဘွဲ့ရကျောင်းသား・Alumni အချက်အလက်",
    currentCompany: "လက်ရှိအလုပ်နေရာ",
    jobType: "အလုပ်အမျိုးအစား",
    workLocation: "အလုပ်လုပ်ရာနေရာ",
    certifications: "ရရှိထားသော အောင်လက်မှတ်",
    alumniMemo: "အလုပ်ပြောင်း・လတ်တလောအခြေအနေ",
    alumniMemoValue: "ဘွဲ့ရပြီးနောက်လည်း ကျောင်းနှင့် ဆက်သွယ်ပြီး နောက်ကျောင်းသားများကို ကုမ္ပဏီမိတ်ဆက်ပေးနိုင်ပါသည်။",
    updateAlumni: "ဘွဲ့ရပြီးနောက်အချက်အလက် Update",
    alumniSaved: "ဘွဲ့ရပြီးနောက်အချက်အလက် update လုပ်ပြီးပါပြီ။",
  },
  en: {
    appTitle: "Student Portal | After-Admission Support",
    heroEyebrow: "Interview Passed Student Portal",
    heroTitle: "Manage everything from enrollment procedures to alumni updates in one portal",
    stageEnrollment: "Enrollment",
    stageEnrollmentDesc: "Profile and documents",
    stageSchoolLife: "School Life",
    stageSchoolLifeDesc: "Attendance, grades, assignments",
    stageGraduation: "Graduation",
    stageGraduationDesc: "Career path and certificates",
    stageAfterGraduation: "After Graduation",
    stageAfterGraduationDesc: "Workplace and certificates",
    studentLogin: "Student Login",
    loginHelp: "Check your procedure status after passing the interview.",
    studentId: "Student ID",
    password: "Password",
    login: "Log in",
    sampleLogin: "Sample: S2026-001 / password",
    portalName: "Student Portal",
    navDashboard: "Dashboard",
    navProfile: "Profile",
    navSchool: "School Managed",
    navCareer: "Graduation & Career",
    navAlumni: "Alumni Update",
    logout: "Log out",
    welcome: "Welcome",
    studentStatus: "Enrollment in progress",
    currentStage: "Current Stage",
    currentStageTitle: "Enrollment procedures after passing the interview",
    currentStageText: "Enter your profile information and wait for school confirmation.",
    journeyEnrollmentText: "Register profile, contact, emergency contact, and desired course",
    journeySchoolText: "Check attendance, grades, assignments, and school notices",
    journeyGraduationText: "Manage graduation details, career path, and job search",
    journeyAlumniText: "Update workplace, job changes, certificates, and alumni information",
    nextTasks: "Next tasks",
    taskBasic: "Confirm basic information",
    taskAddress: "Update address and phone number",
    taskEmergency: "Register emergency contact",
    taskDocs: "Submit enrollment documents",
    schoolNotices: "School notices",
    noticeOrientation: "Enrollment orientation",
    noticeOrientationText: "Sep 3, 10:00, Classroom A",
    noticeAddress: "Address confirmation",
    noticeAddressText: "Please keep your profile up to date",
    noticeCareer: "Career meeting",
    noticeCareerText: "You can register your career path survey",
    profileCategory: "Information entered by the student",
    profileHeading: "Student-entered and updated information",
    fullName: "Full name",
    kana: "Furigana",
    birthday: "Date of birth",
    nationality: "Nationality",
    address: "Address",
    phone: "Phone number",
    email: "Email",
    desiredCourse: "Desired course",
    courseIt: "IT Business Course",
    courseJapanese: "Japanese Course",
    courseCare: "Care Course",
    emergencyContact: "Emergency contact",
    careerHope: "Career hope",
    careerHopeValue: "I hope to work in IT support in Japan.",
    save: "Save",
    profileSaved: "Saved. Please wait for school confirmation.",
    schoolCategory: "Information managed by the school",
    schoolHeading: "Information checked and updated by the school",
    metricStudentNumber: "Student number",
    metricAttendance: "Attendance",
    metricGrade: "Average grade",
    metricAssignments: "Assignments",
    schoolStatus: "School management status",
    tableItem: "Item",
    tableStatus: "Status",
    tableOwner: "Owner",
    rowDocs: "Enrollment document check",
    rowTuition: "Tuition check",
    rowAssignments: "Assignment submission status",
    rowNotice: "School notices",
    statusDone: "Confirmed",
    statusChecking: "Checking",
    statusMissing: "2 missing",
    statusSent: "3 sent",
    ownerOffice: "Office",
    ownerAccounting: "Accounting",
    ownerTeacher: "Homeroom teacher",
    ownerSchool: "School",
    careerHeading: "Graduation and career information",
    careerRegister: "Career path registration",
    expectedGraduation: "Expected graduation date",
    desiredPath: "Desired path",
    pathWorkJapan: "Work in Japan",
    pathStudy: "Continue studying",
    pathReturn: "Return home",
    pathUndecided: "Undecided",
    desiredJob: "Desired job type",
    desiredJobValue: "IT Support / Office Work",
    jobHunting: "Job hunting",
    resume: "Resume preparation",
    waitingSchool: "Waiting for school check",
    interviewPractice: "Interview practice",
    canReserve: "Available to reserve",
    companyIntro: "Company introduction",
    threeCompanies: "3 company candidates",
    alumniCategory: "Information updated after graduation",
    alumniHeading: "Graduate and alumni information",
    currentCompany: "Current company",
    jobType: "Job type",
    workLocation: "Work location",
    certifications: "Certifications",
    alumniMemo: "Job change and recent update",
    alumniMemoValue: "After graduation, I can stay in touch with the school and introduce companies to juniors.",
    updateAlumni: "Update alumni information",
    alumniSaved: "Alumni information updated.",
  },
  vi: {
    appTitle: "Cổng thông tin học sinh | Hỗ trợ sau nhập học",
    heroEyebrow: "Interview Passed Student Portal",
    heroTitle: "Quản lý từ thủ tục nhập học đến cập nhật sau tốt nghiệp trong một cổng thông tin",
    stageEnrollment: "Thủ tục nhập học",
    stageEnrollmentDesc: "Thông tin cá nhân・hồ sơ",
    stageSchoolLife: "Đang học",
    stageSchoolLifeDesc: "Điểm danh・điểm・bài tập",
    stageGraduation: "Tốt nghiệp",
    stageGraduationDesc: "Định hướng・chứng nhận",
    stageAfterGraduation: "Sau tốt nghiệp",
    stageAfterGraduationDesc: "Nơi làm・chứng chỉ",
    studentLogin: "Đăng nhập học sinh",
    loginHelp: "Kiểm tra trạng thái thủ tục sau khi đậu phỏng vấn.",
    studentId: "Mã học sinh",
    password: "Mật khẩu",
    login: "Đăng nhập",
    sampleLogin: "Mẫu: S2026-001 / password",
    portalName: "Cổng học sinh",
    navDashboard: "Bảng điều khiển",
    navProfile: "Thông tin cá nhân",
    navSchool: "Nhà trường quản lý",
    navCareer: "Tốt nghiệp・nghề nghiệp",
    navAlumni: "Cập nhật sau tốt nghiệp",
    logout: "Đăng xuất",
    welcome: "Xin chào",
    studentStatus: "Đang làm thủ tục nhập học",
    currentStage: "Giai đoạn hiện tại",
    currentStageTitle: "Thủ tục nhập học sau khi đậu phỏng vấn",
    currentStageText: "Nhập thông tin cá nhân và chờ nhà trường xác nhận.",
    journeyEnrollmentText: "Đăng ký thông tin cá nhân, liên hệ, liên hệ khẩn cấp và khóa học mong muốn",
    journeySchoolText: "Kiểm tra chuyên cần, điểm, bài tập và thông báo của trường",
    journeyGraduationText: "Quản lý thông tin tốt nghiệp, định hướng và tìm việc",
    journeyAlumniText: "Cập nhật nơi làm, chuyển việc, chứng chỉ và thông tin cựu học sinh",
    nextTasks: "Việc cần làm tiếp theo",
    taskBasic: "Xác nhận thông tin cơ bản",
    taskAddress: "Cập nhật địa chỉ và số điện thoại",
    taskEmergency: "Đăng ký liên hệ khẩn cấp",
    taskDocs: "Nộp hồ sơ nhập học",
    schoolNotices: "Thông báo từ trường",
    noticeOrientation: "Buổi hướng dẫn nhập học",
    noticeOrientationText: "Ngày 3/9, 10:00, Phòng A",
    noticeAddress: "Xác nhận địa chỉ",
    noticeAddressText: "Vui lòng cập nhật thông tin cá nhân mới nhất",
    noticeCareer: "Tư vấn nghề nghiệp",
    noticeCareerText: "Có thể đăng ký khảo sát định hướng nghề nghiệp",
    profileCategory: "Thông tin học sinh tự nhập",
    profileHeading: "Thông tin học sinh tự nhập và cập nhật",
    fullName: "Họ tên",
    kana: "Furigana",
    birthday: "Ngày sinh",
    nationality: "Quốc tịch",
    address: "Địa chỉ",
    phone: "Số điện thoại",
    email: "Email",
    desiredCourse: "Khóa học mong muốn",
    courseIt: "Khóa IT Business",
    courseJapanese: "Khóa tiếng Nhật",
    courseCare: "Khóa chăm sóc",
    emergencyContact: "Liên hệ khẩn cấp",
    careerHope: "Nguyện vọng việc làm",
    careerHopeValue: "Tôi muốn làm công việc hỗ trợ IT tại Nhật Bản.",
    save: "Lưu",
    profileSaved: "Đã lưu. Vui lòng chờ nhà trường xác nhận.",
    schoolCategory: "Thông tin do nhà trường quản lý",
    schoolHeading: "Thông tin nhà trường xác nhận và cập nhật",
    metricStudentNumber: "Mã học sinh",
    metricAttendance: "Chuyên cần",
    metricGrade: "Điểm trung bình",
    metricAssignments: "Bài tập",
    schoolStatus: "Trạng thái quản lý của trường",
    tableItem: "Mục",
    tableStatus: "Trạng thái",
    tableOwner: "Phụ trách",
    rowDocs: "Kiểm tra hồ sơ nhập học",
    rowTuition: "Kiểm tra học phí",
    rowAssignments: "Tình trạng nộp bài tập",
    rowNotice: "Thông báo từ trường",
    statusDone: "Đã xác nhận",
    statusChecking: "Đang kiểm tra",
    statusMissing: "Còn thiếu 2",
    statusSent: "Đã gửi 3",
    ownerOffice: "Văn phòng",
    ownerAccounting: "Kế toán",
    ownerTeacher: "Giáo viên chủ nhiệm",
    ownerSchool: "Nhà trường",
    careerHeading: "Thông tin tốt nghiệp và định hướng",
    careerRegister: "Đăng ký định hướng",
    expectedGraduation: "Ngày dự kiến tốt nghiệp",
    desiredPath: "Định hướng mong muốn",
    pathWorkJapan: "Làm việc tại Nhật",
    pathStudy: "Học tiếp",
    pathReturn: "Về nước",
    pathUndecided: "Chưa quyết định",
    desiredJob: "Loại công việc mong muốn",
    desiredJobValue: "Hỗ trợ IT / Văn phòng",
    jobHunting: "Tìm việc",
    resume: "Chuẩn bị sơ yếu lý lịch",
    waitingSchool: "Chờ trường kiểm tra",
    interviewPractice: "Luyện phỏng vấn",
    canReserve: "Có thể đặt lịch",
    companyIntro: "Giới thiệu công ty",
    threeCompanies: "Có 3 công ty ứng viên",
    alumniCategory: "Thông tin cập nhật sau tốt nghiệp",
    alumniHeading: "Thông tin cựu học sinh・Alumni",
    currentCompany: "Công ty hiện tại",
    jobType: "Loại công việc",
    workLocation: "Nơi làm việc",
    certifications: "Chứng chỉ",
    alumniMemo: "Chuyển việc・cập nhật gần đây",
    alumniMemoValue: "Sau khi tốt nghiệp, tôi vẫn có thể liên lạc với trường và giới thiệu công ty cho khóa sau.",
    updateAlumni: "Cập nhật thông tin sau tốt nghiệp",
    alumniSaved: "Đã cập nhật thông tin sau tốt nghiệp.",
  },
};

let currentView = "dashboard";
let currentLang = "ja";

function t(key) {
  return translations[currentLang][key] || translations.ja[key] || key;
}

function showPortal() {
  loginView.classList.add("hidden");
  portalView.classList.remove("hidden");
  setView("dashboard");
}

function showLogin() {
  portalView.classList.add("hidden");
  loginView.classList.remove("hidden");
}

function setView(viewName) {
  currentView = viewName;

  Object.entries(pages).forEach(([key, page]) => {
    page.classList.toggle("active", key === viewName);
  });

  navItems.forEach((item) => {
    item.classList.toggle("active", item.dataset.view === viewName);
  });

  pageTitle.textContent = t(`nav${viewName.charAt(0).toUpperCase()}${viewName.slice(1)}`);
}

function applyLanguage(lang) {
  currentLang = lang;
  document.documentElement.lang = lang === "my" ? "my" : lang;
  document.title = t("appTitle");

  document.querySelectorAll("[data-i18n]").forEach((element) => {
    element.textContent = t(element.dataset.i18n);
  });

  document.querySelectorAll("[data-i18n-input]").forEach((element) => {
    element.value = t(element.dataset.i18nInput);
  });

  document.querySelectorAll("[data-i18n-value]").forEach((element) => {
    element.value = t(element.dataset.i18nValue);
  });

  languageButtons.forEach((button) => {
    button.classList.toggle("active", button.dataset.lang === lang);
  });

  setView(currentView);
}

loginForm.addEventListener("submit", (event) => {
  event.preventDefault();
  showPortal();
});

logoutButton.addEventListener("click", showLogin);

navItems.forEach((item) => {
  item.addEventListener("click", () => setView(item.dataset.view));
});

languageButtons.forEach((button) => {
  button.addEventListener("click", () => applyLanguage(button.dataset.lang));
});

document.querySelectorAll("[data-view-target]").forEach((button) => {
  button.addEventListener("click", () => setView(button.dataset.viewTarget));
});

document.querySelector("#profileForm").addEventListener("submit", (event) => {
  event.preventDefault();
  const message = document.querySelector("#saveMessage");
  message.textContent = t("profileSaved");
  window.setTimeout(() => {
    message.textContent = "";
  }, 3500);
});

document.querySelector("#alumniSave").addEventListener("click", () => {
  const message = document.querySelector("#alumniMessage");
  message.textContent = t("alumniSaved");
  window.setTimeout(() => {
    message.textContent = "";
  }, 3500);
});

applyLanguage(currentLang);
